import logging
import httpx
from app.config import settings

logger = logging.getLogger("email")

class EmailService:
    def __init__(self):
        self.api_key = settings.RESEND_API_KEY
        self.from_email = settings.RESEND_FROM_EMAIL
        self.enabled = bool(self.api_key)

    def send_build_success_email(self, to_email: str, project_name: str, preview_url: str, github_url: str) -> bool:
        """Sends a beautiful HTML email notifying the user of build success."""
        subject = f"🚀 Build Complete: Your application '{project_name}' is ready!"
        
        html_content = f"""
        <div style="font-family: sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #e2e8f0; border-radius: 8px;">
            <h2 style="color: #0f172a; margin-bottom: 10px;">Your App is Built & Deployed!</h2>
            <p style="color: #475569; line-height: 1.6;">Great news! The Autonomous Agent has completed building <strong>{project_name}</strong>. The entire application was compiled, verified, and successfully pushed to git in the cloud.</p>
            
            <div style="margin: 25px 0; padding: 15px; background-color: #f8fafc; border-radius: 6px;">
                <p style="margin: 5px 0; color: #334155;"><strong>Preview Web URL:</strong> <a href="{preview_url}" style="color: #2563eb; text-decoration: none;">{preview_url}</a></p>
                <p style="margin: 5px 0; color: #334155;"><strong>GitHub Repository:</strong> <a href="{github_url}" style="color: #2563eb; text-decoration: none;">{github_url}</a></p>
            </div>
            
            <a href="{settings.FRONTEND_URL}/project/{project_name.lower().replace(' ', '-')}" style="display: inline-block; padding: 10px 20px; background-color: #0f172a; color: #ffffff; text-decoration: none; border-radius: 6px; font-weight: bold; text-align: center;">Open Workspace Dashboard</a>
            
            <hr style="border: 0; border-top: 1px solid #e2e8f0; margin: 25px 0;" />
            <p style="font-size: 12px; color: #94a3b8;">This email was automatically generated by the Autonomous Cloud IDE platform. You can safely close your laptop while builds are running.</p>
        </div>
        """
        
        return self._send_email(to_email, subject, html_content)

    def send_build_failed_email(self, to_email: str, project_name: str, error_snippet: str) -> bool:
        """Sends a beautiful HTML email notifying the user of build failure."""
        subject = f"⚠️ Build Failed: Action required for project '{project_name}'"
        
        html_content = f"""
        <div style="font-family: sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #e2e8f0; border-radius: 8px;">
            <h2 style="color: #ef4444; margin-bottom: 10px;">Build Interrupted</h2>
            <p style="color: #475569; line-height: 1.6;">The AI developer agent encountered a critical compilation error while building <strong>{project_name}</strong> and was unable to complete the autonomous workflow.</p>
            
            <div style="margin: 25px 0; padding: 15px; background-color: #fef2f2; border-left: 4px solid #ef4444; border-radius: 4px; font-family: monospace; white-space: pre-wrap; font-size: 14px; color: #991b1b;">
<strong>Error snippet:</strong>
{error_snippet}
            </div>
            
            <a href="{settings.FRONTEND_URL}/project/{project_name.lower().replace(' ', '-')}" style="display: inline-block; padding: 10px 20px; background-color: #ef4444; color: #ffffff; text-decoration: none; border-radius: 6px; font-weight: bold; text-align: center;">Inspect Full Build Logs</a>
            
            <hr style="border: 0; border-top: 1px solid #e2e8f0; margin: 25px 0;" />
            <p style="font-size: 12px; color: #94a3b8;">This email was automatically generated by the Autonomous Cloud IDE platform.</p>
        </div>
        """
        
        return self._send_email(to_email, subject, html_content)

    def _send_email(self, to_email: str, subject: str, html_content: str) -> bool:
        """Helper to post the email request to Resend API or logs."""
        if not self.enabled:
            logger.info(f"[SIMULATED EMAIL DISPATCH] To: {to_email} | Subject: '{subject}'")
            return True

        headers = {
            "Authorization": f"Bearer {self.api_key}",
            "Content-Type": "application/json"
        }
        
        payload = {
            "from": self.from_email,
            "to": [to_email],
            "subject": subject,
            "html": html_content
        }

        try:
            with httpx.Client() as client:
                res = client.post("https://api.resend.com/emails", headers=headers, json=payload)
                if res.status_code == 200 or res.status_code == 201:
                    logger.info(f"Successfully sent email to {to_email}")
                    return True
                else:
                    logger.error(f"Resend API email transmission failed: {res.text}")
                    return False
        except Exception as e:
            logger.error(f"Failed to transmit email via Resend: {e}")
            return False

email_service = EmailService()
